# Generated by Django 5.0 on 2023-12-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hotel_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='home.cities'),
        ),
    ]
