# Generated by Django 5.0 on 2023-12-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_hotel_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
