# Generated by Django 5.0 on 2023-12-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_hotel_city_name_delete_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city_name',
        ),
    ]
