# Generated by Django 5.0 on 2023-12-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hotel_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city_name',
        ),
    ]
