# Generated by Django 5.0 on 2023-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_hotel_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
