# Generated by Django 5.0 on 2023-12-24 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cities_alter_hotel_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_name',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='home.cities'),
        ),
    ]
