# Generated by Django 5.0 on 2023-12-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_cities_city_id_alter_hotel_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city_name',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
